# Generated by Django 2.2.10 on 2020-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=294)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField(unique=True)),
                ('download_url', models.URLField(unique=True)),
            ],
        ),
    ]
