# Generated by Django 2.2.10 on 2020-03-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicId',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taskapp.Picture')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
