# Generated by Django 2.2.10 on 2020-03-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_picid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
