# Generated by Django 2.2.10 on 2020-03-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20200309_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picid',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='taskapp.Picture'),
        ),
    ]
